name: Ubuntu 20.04 Swift CI

on:
  push:
    branches: [development, main]

jobs:

  exec-ci:
    runs-on: ubuntu-20.04

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
            swift-version: "5.6.1"

      - name: Setup SSH Key
        run: | 
            rm -rf ~/.ssh
            mkdir -m 0700 ~/.ssh
            echo "${{ secrets.DEPLOYSSHSECRET }}" > ~/.ssh/id_ed25519
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJSXIu3pdrF5VbgvvBt6rKzVidV6olrGIbxJDDUgIhsi lay-preps-0h@icloud.com" > ~/.ssh/id_ed25519.pub
            chmod 0600 ~/.ssh/id_ed25519
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519

      - name: Clone guunits
        uses: actions/checkout@v2
        with:
            repository: mipalgu/guunits
            path: guunits

      - name: Install guunits
        run: |
            cd guunits/guunits
            cmake -B build
            cd build
            make
            sudo make install

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
        run: swift test
