name: Windows Latest Swift CI

on:
  push:
    branches: [development, main]

jobs:

  exec-ci:
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
            branch: swift-5.6.2-release
            tag: 5.6.2-RELEASE

      - name: Install guunits
        uses: mipalgu/install-guunits@main

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Debug Build
        shell: pwsh
        run: swift build -c debug -Xcc -I"C:\Program Files (x86)\guunits\include" -Xlinker -L"C:\Program Files (x86)\guunits\lib"

      - name: Release build
        shell: pwsh
        run: swift build -c release -Xcc -I"C:\Program Files (x86)\guunits\include" -Xlinker -L"C:\Program Files (x86)\guunits\lib"
