name: DocC Documentation

on:
  push:
    branches: [ main ]

jobs:

  generate-documentation:
    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6.1"

      - name: Install guunits
        uses: mipalgu/install-guunits@main

      - name: Clone Repository 
        uses: actions/checkout@v2

      - name: Generate Documentation
        run: swift package --allow-writing-to-directory ./docs generate-documentation --disable-indexing --transform-for-static-hosting --hosting-base-path swift_GUUnits --output-path ./docs

      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
